# joint_limits.yaml allows the dynamics properties specified in the URDF 
# to be overwritten or augmented as needed.

# Scaling factors for MoveIt (set to 1.0 for full speed)
default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14  # 180°/s
    has_acceleration_limits: true
    max_acceleration: 3.0  # Ajusta según el hardware
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3.0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 4.0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 4.0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 4.0

  # 🚀 Agregando la garra (Robotiq 85)
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  robotiq_85_right_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: true
    max_acceleration: 1.0
